name: Test Packages Installation

on:
  push:
    branches: ['main']

jobs:
  test-packages-installation:
    runs-on: ubuntu-latest
    name: Test Packages Installation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install
